#server:
#  port: 9001
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
      - id: Movie-Service
        uri: lb://MOVIE-SERVICE
        predicates:
        - Path=/movie-api/**
      - id: COUPON-SERVICE
        uri: lb://COUPON-SERVICE
        predicates:
        - Path=/coupon-api/**     
    discovery:
      enabled: true
      
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    
    
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
     defaultZone: http://localhost:8761/eureka       